project:
  type: website
  output-dir: docs

website:
  title: "MAE 1001 [Fall 2025]"
  page-footer: "This is a Quarto website. To learn more about Quarto websites visit <https://quarto.org/docs/websites>.<br> Contact: [Kartik Bulusu](mailto:bulusu@email.gwu.edu)<br> &copy; 2025 All rights reserved"
  search: true
  page-navigation: true
  bread-crumbs: true
  sidebar:
    style: floating
    # collapse-level: 2
    background: primary
    foreground: secondary
    # fontcolor: black
    left:
      # - href: index.qmd
      #   text: Home
      # - about.qmd
      # - policies.qmd
      # - text: "Getting Started with MAE1001"
      #   menu:
      #     - href: install-editor.qmd
      # - schedule.qmd       
      # - text: "Notes"    
    contents: 
      - href: index.qmd
        text: Home
      - section: "Getting Started"
        contents: 
          - href: getting_started.qmd
            text: MUST READ Preliminaries
          - href: install-editor.qmd
            text: MUST DO Software Installations        
      - href: guidelines.qmd
        text: Course Policies        
      - href: objectives.qmd
        text: Learning Objectives  
      - href: agenda.qmd
        text: Schedule
      - href: standup.qmd
        text: Student Panel        
      # - href: standup.qmd
      #   text: Student Panelists   
      # - href: guests.qmd
      #   text: Guest speakers
      - href: instructor.qmd
        text: Instruction Team

          # - section: "Real VNC&reg; Viewer"
          #   contents: 
          #     - href: realvnc-mac.qmd
          #       text: Mac
          #     - href: realvnc-windows.qmd
          #       text: Windows   
          # - href: thingspeak.qmd
          #   text: ThingSpeak
          # - section: "Connecting your laptop to the Raspberry Pi"
          #   contents: 
          #     - href: realvnc-mac-connect.qmd
          #       text: Mac
          #     - href: realvnc-windows-connect.qmd
          #       text: Windows                       


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    author: Kartik Bulusu
    date: now
    # monofont: "DejaVu Sans Mono"
    # mainfont: "Roboto"

  # navbar:
  #   background: primary
  #   foreground: secondary
  #   # fontcolor: black
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - about.qmd
  #     - policies.qmd
  #     - text: "Getting Started"
  #       menu:
  #         - href: install-editor.qmd
  #     - schedule.qmd       
  #     - text: "Notes"
      #   menu: 
      #     - href: Week0.qmd 
      #     - href: Week1.qmd
      #     - href: Week2.qmd
      #     - href: Week2-Mohammad-PrattWhitney-Lecture.qmd
      #     - href: Week3.qmd
      #     - href: Week4.qmd
      #     - href: Week4-JitishKolanjery-Google-Lecture.qmd
      #     - href: Week5.qmd
      #     - href: Week6.qmd  
      #     - href: Week6-ChowdaryYanamadala-ARM-Lecture.qmd  
      #     - href: Midterm_Presentations_Spring2024.qmd
      #     - href: Week8.qmd  
      #     - href: Week8-JakeWhitton-Demo-Lecture.qmd           
      # #     - href: Week6-Nuzum-Innovyz-Lecture.qmd
      #     - href: Week9.qmd    
      #     - href: Week10.qmd    
      #     - href: Week10-ChrisRodley-SnapGroup-Lecture.qmd            
      #     - href: Week11.qmd    
      #     - href: Week11-ThomasFarmer-UPenn-Lecture.qmd             
      # #   - href: Week10-Pottier-ARM-Lecture.qmd   
      #     - href: Week12.qmd  
      #     - href: Week12-AnuragBhatnagar-ShiftAltCap-Lecture.qmd
      #     - href: Week13-Thoughts_FutureDirections.qmd  
      #     - href: Week14-FinalProject_Gallery.qmd          
      # - text: "Python Primer"  
      #   menu: 
      #       - text: "Basics"
      #         href: ./python_primer/basics.qmd
      #       # - text: "Functions"
      #       #   href: ./python_primer/functions.qmd
      #       - text: "Constructs"
      #         href: ./python_primer/constructs.qmd
      #       - text: "Data types"
      #         href: ./python_primer/data_types.qmd
            
          # - href:  ./python_primer/unt0/modules/module0.qmd
      # # - weekly.qmd
      # - resources.qmd      
      # - instructor.qmd

# format:
#   html:
#     theme: Yeti
#     css: styles.css
#     toc: true

