---
title: "Agenda"
subtitle: The agenda may be updated with minor changes during workshop
format:
  html:
    code-copy: false
---

<html>
<head>
    <style>
        body {
            -webkit-user-select: none; /* Safari */
            -moz-user-select: none; /* Firefox */
            -ms-user-select: none; /* IE10+/Edge */
            user-select: none; /* Standard */
        }
    </style>
</head>
<body>

:::{.callout-important}
**Referencing the content in this workshop:**

Bulusu, Kartik V. (2024, October 12). Connect, Compute and Communicate! Practical introduction to a DIY internet of things system. [Workshop for the IEEE Northern Virigina Section and IEEE Computer Society]. Department of Mechanical and Aerospace Engineering, The George Washington University.
:::

:::{.callout-important}
- The workshop is desinged with active learning modules with limited number of hardware components. 
- You are strongly encouraged to bring your own personal machine or laptop and participate with the [prerequisites](install-editor.qmd) installed.
 - Follow the instructions provided carefully and complete the required installations needed for this workshop. ([See prerequisites](install-editor.qmd))
 - Once you finish the **Steps 1, 2 and 3 in the installation instructions** in [prerequisites](install-editor.qmd), fill out the [Pre-workshop survey form](https://tinyurl.com/yrkacfd9). 
 - **You will be automatically entered into a raffle in the workshop on 10/12/2024 if you complete the installation check-in form.**
:::

```{=html}
<table style="width:100%">
    <colgroup>
        <col style="width:20%">
        <col style="width:30%">
        <col style="width:50%">

    </colgroup>
    <thead>
        <tr class="table-primary">
            <th>Date</th>
            <th>Topic(s)</th>
            <th scope="col">Description and the $\mu$-lab </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>October 10, 2025</td>
            <td>Opening remarks and announcements</td>
            <td> </td>
        </tr>
        <tr class="table-active">
            <td>October 17, 2025</td>
            <td>Prereq-checks and balances </td>
            <td>
                <ul>
                    <li>Installations on your personal machines (Mac or Windows)):</li>  
                    <ul>
                        <li>Real VNC</li> 
                    </ul> 
                    <li>Hardware description and support:</li>  
                    <ul>
                        <li>Establish a tethered connection</li>
                        <li>Create a **free** <a href="https://thingspeak.com/login?skipSSOCheck=true"target="_blank"> ThingSpeak</a> account</li> 
                        <li>Get an **optional free** ThingView account of your mobile device</li>
                    </ul> 
                </ul>   
            </td>     
        </tr>
        <tr>
            <td>October 24, 2025</td>
            <td>Warm-up activity </td>
            <td>Pre-workshop survery and results</td>
        </tr>
        <tr class="table-active">
            <td>October 31, 2025</td>
            <td> Brief history of IoT and What we do now</td>
            <td>                
                <ul>
                    <li>IoT and Edge Computing [The big pictures]</li> 
                    <li>Getting familiar with the Raspberry Pi 4B</li>
                    <li>Python programming using Thonny</li> 
                </ul> 
            </td>
        </tr>
        <tr>
            <td>November 07, 2025</td>
            <td>Break / Discussion</td>
            <!-- <td>02/14/2024</td> -->
            <!-- <td>02/16/2024</td>
            <td>Unit 0 » Module 5 (Due <b>February 19, 2024</b> by <b>11:59 PM</b>)</td> -->
        </tr>
        <tr class="table-active">
            <td>1November 14, 2025</td>
            <td>What is a "Thing" in IoT?</td>
            <td>Presentation / Discussion</td>
            <!-- <td>02/23/2024</td>
            <td>Unit 0 » Module 6 (Due <b>February 26, 2024</b> by <b>11:59 PM</b>)</td> -->
        </tr>
        <tr>
            <td>November 21, 2025</td>
            <td>Break / Discussion</td>
            <!-- <td>Assignment 1 (Due  <b>March 01, 2024</b> by <b>11:59 PM</b>) & Unit 1 » Module 0 (Due <b>March 04, 2024</b> by <b>11:59 PM</b>)</td> -->
        </tr>
        <tr class="table-active">
            <td>November 28, 2025</td>
            <td>Blinking LEDs</td>
            <td>
                <ul>
                    <li style="color:black">Python skelton code for running programs on the Raspberry Pi</li>
                    <li style="color:black">Using Thonny to blink LEDs</li>
                    <li>dweet.io - it's like the Twitter of Things <a href="https://dweet.io"target="_blank"> dweet</a></li>
                    <li style="color:black">Fetching data from dweet</li>
                    <li style="color:black">dweet an LED - Your first IoT program</li>
                    <li style="color:black">Raspberry Pi messaging with Python scripts</li>
                </ul>
            </td>    
            <!-- <td>03/08/2024</td>
            <td>Unit 1 » Module 1 (Due <b>March 11, 2024</b> by <b>11:59 PM</b>)</td> -->
        </tr>
        <tr>
            <td>December 05, 2025</td>
            <td>Break / Discussion</td>
            <!-- <td><b>No Lab</b></td>
            <td>Nothing assigned</td> -->
        </tr>
        <tr class="table-active">
            <td>2:05 - 2:45</td>
            <td>Demonstration of SenseHat sensor module</td>
            <td>
                <ul>
                    <li>Implementation of MQTT using <a href="https://thingspeak.com/login?skipSSOCheck=true"target="_blank"> ThingSpeak</a></li>
                    <li><strong>Implementation of ThingSpeak MQTT with SenseHat</strong></li>
                </ul>
            </td>  
        </tr>
        <tr>
            <td>2:45 - 3:00</td>
            <td>Closing remarks</td>
            <td>Summary, survey and what's in the future</td>
            <!-- <td>03/29/2024</td>
            <td>Unit 1 » Module 3 & Assignment 2 (Due <b>April 01, 2024</b> by <b>11:59 PM</b>)</td> -->
        </tr>
        <!-- <tr class="table-active">
            <td>Week 11 [04/01/2024]</td>
            <td><code><b>while</b></code> loops, I/O</td>
            <td>04/03/2024</td>
            <td>04/05/2024</td>
            <td>Unit 1 » Module 4 & Module 5 (Due <b>April 10, 2024</b> by <b>11:59 PM</b>)</td>
        </tr>
        <tr>
            <td>Week 12 [04/08/2024]</td>
            <td><code><b>numpy</b></code> Arrays</td>
            <td>04/10/2024</td>
            <td>04/12/2024</td>
            <td>Assignment 3 (Due <b>April 20, 2024</b> by <b>11:59 PM</b>)</td>
        </tr>
        <tr class="table-active">
            <td><b>Week 13 [04/15/2024]</b></td>
            <td><b><u>Examination</u></b>
                <br><em>Location:</em> <b>Lecture room 1957 E Room 213</b>
                <br><em>Start time:</em> <b>3:45 PM</b></td>
            <td>04/17/2024</td>
            <td>04/19/2024</td>
            <td>Unit 2 » Module 0 (Due <b>April 25, 2024</b> by <b>11:59 PM</b>)</td>
        </tr> -->
        <!-- <tr>
            <td>Week 14 [04/22/2024]</td>
            <td>Advanced Topics</td>
            <td>04/24/2024</td>
            <td>04/26/2024</td>
            <td>Unit 2 » Module 1 & Assignemnt 4 (Due <b>May 01, 2024</b> by <b>11:59 PM</b>)</td>
        </tr> -->
        <!-- <tr class="table-active">
            <td>Week 15 [04/29/2024]</td>
            <td><em>Extra Lecture</em></td>
        </tr> -->
        <!-- <tr>
            <td>[04/30/2024]</td>
            <td>Make up Day</td>
        </tr> -->
        <!-- <tr class="table-active">
            <td>[05/01/2024]</td>
            <td>Designated Monday</td>
        </tr> -->
        <!-- <tr>
            <td>Week of <b>May 04</b> to <b>May 10</b></td>
            <td><b>Exam Week</b></td>
        </tr> -->
        
    </tbody>
</table>


-- Fall Break (no classes)	Thursday - Friday, October 9-10, 2025
-- Thanksgiving Break (no classes)	Monday, November 24 - Saturday, November 29, 2025
-- Last Day of Classes	Monday, December 8, 2025
-- Designated Thursday	Tuesday, December 9, 2025
-- Designated Friday	Wednesday, December 10, 2025
-- Make-up/Reading Day	Thursday, December 11, 2025
-- Final Exams	Friday, December 12 - Thursday, December 18, 2025

```
<!-- </body>
</html> -->

:::{.callout-important}
<!-- - Our staff is limiting the use of Linux OS-based laptops and cannot support them this semester.  -->
**Kindly note that**

- Your personal machine should be able to connect to the WiFi network provided at the location. 

- **Tech support is not provided** unless there are minor issues that could be sorted out.  
- **We prefer that your computer**
    - is a laptop, with either MacOS 12+ or Windows 10+ operating system 
    - has a standard US keyboard layout i.e, a QWERTY keyboard. 
        - The QWERTY (pronounced KWEHR-tee) keyboard is the standard typewriter and computer keyboard in countries that use a Latin-based alphabet.
:::
