---
title: "Learning Objectives"
format: 
  html:
    code-copy: false
---

<html>
<head>
    <style>
        body {
            -webkit-user-select: none; /* Safari */
            -moz-user-select: none; /* Firefox */
            -ms-user-select: none; /* IE10+/Edge */
            user-select: none; /* Standard */
        }
    </style>
</head>
<body>

:::{.callout-important}
**Referencing the content in this workshop:**

Bulusu, Kartik V. (2024, October 12). Connect, Compute and Communicate! Practical introduction to a DIY internet of things system. [Workshop for the IEEE Northern Virigina Section and IEEE Computer Society]. Department of Mechanical and Aerospace Engineering, The George Washington University.
:::

<!-- ## Course Learning Outcomes -->
1. Gain basic, hands-on knowledge of Raspberry Pi hardware with Python programming language
2. Gain insight on IoT applications and edge computing strategies with the Raspberry Pi
3. Gain exposure to IoT automation platforms such as ThingSpeak 
4. Implement one Raspberry Pi-based IoT system
<!-- 5. Gain insight on edge computing strategies with the Raspberry Pi -->
<!-- 6. Gain understanding of industry 4.0 exposure via invited speakers and case studies -->



